# Generated by Django 5.0.1 on 2024-02-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_image_image'),
        ('blog', '0008_rename_name_comment_author'),
    ]

    operations = [
    ]
