version: '3'

services:
  postgres_db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./blogproject/backend/static:/app/static
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    env_file:
      - .env
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - frontend:/app/build


  nginx:
    build:
      context: ./nginx
    volumes:
      - ./blogproject/backend/static:/app/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
   
volumes:
  postgres_data:
  frontend:
